language: python
python:
  - "3.6"

before_install:
- git clone --depth 1 https://github.com/KiCad/kicad-library-utils /home/travis/build/kicad-library-utils

script:
- python /home/travis/build/kicad-library-utils/schlib/checklib.py -v $TRAVIS_BUILD_DIR/*.lib
- python /home/travis/build/kicad-library-utils/pcb/check_kicad_mod.py -v $TRAVIS_BUILD_DIR/Chameleon_Electronics.pretty/*.kicad_mod
